FROM python:3.9-slim

WORKDIR /app

# Instalacija zavisnosti
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# U dev modu ne moramo kopirati sav kod ako koristimo volumes, 
# ali je dobro imati ga za inicijalni build
COPY . .

CMD ["python", "run.py"]