FROM python:3.9-slim

WORKDIR /app

# Prvo kopiramo requirements i instaliramo sve sa spiska
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiramo ostatak koda
COPY . .

# Pokretanje: Koristimo eventlet i varijablu $PORT (bez navodnika i zagrada)
CMD gunicorn --worker-class eventlet --bind 0.0.0.0:$PORT run:app